import { useState, useEffect } from 'react';
import { requestFcmToken, onMessageListener } from '../lib/firebase';

export const useFirebaseAlerts = (userLanguage: string) => {
  const [fcmToken, setFcmToken] = useState<string | null>(null);
  const [incomingAlert, setIncomingAlert] = useState<{ title: string, body: string } | null>(null);

  const requestNotificationPermission = async () => {
    if (typeof window !== 'undefined' && 'Notification' in window) {
      const permission = await Notification.requestPermission();
      if (permission === 'granted') {
        const token = await requestFcmToken("BEBZl6-WrZ0gOSVSZLeWNUhgMeejDpVqAF-WUgxomclCoSPe9ZrpLYyGHPdGrI2BkqzjA_Iev-JZD5yDGWAZynM"); // Replace
        if (token) {
           setFcmToken(token);
           console.log(`[FCM Sync] Token ready for backend language -> ${userLanguage}`);
           return token;
        }
      } else {
         console.warn("Notification permission denied by user.");
      }
    }
    return null;
  };

  useEffect(() => {
    if (fcmToken) {
      // Actively listen for incoming push messages generated by the `scheduleEngine.ts` when the app is OPEN
      onMessageListener().then((payload: any) => {
        console.log("Foreground Message Triggered: ", payload);
        if (payload?.notification) {
           setIncomingAlert({
              title: payload.notification.title,
              body: payload.notification.body
           });
           
           // You can use motion/react toast overlay here when an alert hits live
        }
      }).catch(err => console.log('Message listener failed: ', err));
    }
  }, [fcmToken]);

  return { requestNotificationPermission, fcmToken, incomingAlert, clearAlert: () => setIncomingAlert(null) };
};
