export const sop100Days = [
  { doc: 1, feed: 2, action: 'Probiotic', alert: 'Stocking stress' },
  { doc: 2, feed: 2, action: '—', alert: 'Observe' },
  { doc: 3, feed: 3, action: 'Probiotic', alert: 'Stable' },
  { doc: 4, feed: 3, action: '—', alert: '—' },
  { doc: 5, feed: 3, action: 'Mineral (5 kg)', alert: 'Molting' },
  { doc: 6, feed: 3, action: '—', alert: '—' },
  { doc: 7, feed: 4, action: 'Probiotic', alert: '—' },
  { doc: 8, feed: 4, action: '—', alert: '—' },
  { doc: 9, feed: 4, action: 'Mineral', alert: '—' },
  { doc: 10, feed: 4, action: 'Probiotic', alert: 'DOC 10 check' },
  
  { doc: 11, feed: 5, action: 'Gut probiotic', alert: 'Start' },
  { doc: 12, feed: 5, action: '—', alert: '—' },
  { doc: 13, feed: 6, action: 'Probiotic', alert: '—' },
  { doc: 14, feed: 6, action: 'Mineral', alert: '—' },
  { doc: 15, feed: 7, action: 'Vitamin C', alert: 'Immunity' },
  { doc: 16, feed: 7, action: '—', alert: '—' },
  { doc: 17, feed: 8, action: 'Probiotic', alert: '—' },
  { doc: 18, feed: 8, action: '—', alert: '—' },
  { doc: 19, feed: 9, action: 'Mineral', alert: '—' },
  { doc: 20, feed: 10, action: 'Probiotic', alert: 'DOC 20' },

  { doc: 21, feed: 12, action: 'Probiotic', alert: 'Risk start' },
  { doc: 22, feed: 13, action: '—', alert: '—' },
  { doc: 23, feed: 14, action: 'Mineral', alert: '—' },
  { doc: 24, feed: 15, action: 'Probiotic', alert: '—' },
  { doc: 25, feed: 15, action: 'Immunity booster', alert: 'Vibriosis' },
  { doc: 26, feed: 16, action: '—', alert: '—' },
  { doc: 27, feed: 17, action: 'Mineral', alert: '—' },
  { doc: 28, feed: 18, action: 'Probiotic', alert: '—' },
  { doc: 29, feed: 19, action: '—', alert: '—' },
  { doc: 30, feed: 20, action: 'Probiotic', alert: 'Critical' },

  { doc: 31, feed: 22, action: 'Mineral', alert: 'Critical' },
  { doc: 32, feed: 23, action: 'Probiotic', alert: '—' },
  { doc: 33, feed: 24, action: '—', alert: '—' },
  { doc: 34, feed: 25, action: 'Immunity', alert: '—' },
  { doc: 35, feed: 26, action: 'Probiotic', alert: '—' },
  { doc: 36, feed: 27, action: 'Mineral', alert: '—' },
  { doc: 37, feed: 28, action: '—', alert: '—' },
  { doc: 38, feed: 29, action: 'Probiotic', alert: '—' },
  { doc: 39, feed: 30, action: '—', alert: '—' },
  { doc: 40, feed: 30, action: 'Vitamin', alert: 'WSSV Risk' },
  { doc: 41, feed: 31, action: 'Mineral', alert: '—' },
  { doc: 42, feed: 32, action: 'Probiotic', alert: '—' },
  { doc: 43, feed: 33, action: '—', alert: '—' },
  { doc: 44, feed: 34, action: 'Mineral', alert: '—' },
  { doc: 45, feed: 35, action: 'Probiotic', alert: 'DOC 45' },

  { doc: 46, feed: 36, action: 'Probiotic', alert: 'Growth' },
  { doc: 47, feed: 37, action: '—', alert: '—' },
  { doc: 48, feed: 38, action: 'Mineral', alert: '—' },
  { doc: 49, feed: 39, action: '—', alert: '—' },
  { doc: 50, feed: 40, action: 'Liver tonic', alert: 'Health' },
  { doc: 51, feed: 41, action: 'Probiotic', alert: '—' },
  { doc: 52, feed: 42, action: '—', alert: '—' },
  { doc: 53, feed: 43, action: 'Mineral', alert: '—' },
  { doc: 54, feed: 44, action: '—', alert: '—' },
  { doc: 55, feed: 45, action: 'Probiotic', alert: '—' },
  { doc: 56, feed: 46, action: 'Mineral', alert: '—' },
  { doc: 57, feed: 47, action: '—', alert: '—' },
  { doc: 58, feed: 48, action: 'Probiotic', alert: '—' },
  { doc: 59, feed: 49, action: '—', alert: '—' },
  { doc: 60, feed: 50, action: 'Mineral', alert: 'DOC 60' },

  { doc: 61, feed: 51, action: 'Probiotic', alert: 'Growth' },
  { doc: 62, feed: 52, action: '—', alert: '—' },
  { doc: 63, feed: 53, action: 'Mineral', alert: '—' },
  { doc: 64, feed: 54, action: '—', alert: '—' },
  { doc: 65, feed: 55, action: 'Probiotic', alert: '—' },
  { doc: 66, feed: 56, action: '—', alert: '—' },
  { doc: 67, feed: 57, action: 'Mineral', alert: '—' },
  { doc: 68, feed: 58, action: '—', alert: '—' },
  { doc: 69, feed: 59, action: 'Probiotic', alert: '—' },
  { doc: 70, feed: 60, action: 'Immunity', alert: 'Check' },
  { doc: 71, feed: 60, action: '—', alert: '—' },
  { doc: 72, feed: 61, action: 'Mineral', alert: '—' },
  { doc: 73, feed: 62, action: '—', alert: '—' },
  { doc: 74, feed: 63, action: 'Probiotic', alert: '—' },
  { doc: 75, feed: 64, action: '—', alert: '—' },
  { doc: 76, feed: 65, action: 'Mineral', alert: '—' },
  { doc: 77, feed: 66, action: '—', alert: '—' },
  { doc: 78, feed: 67, action: 'Probiotic', alert: '—' },
  { doc: 79, feed: 68, action: '—', alert: '—' },
  { doc: 80, feed: 60, action: 'Mineral', alert: 'DOC 80' },

  { doc: 81, feed: 60, action: 'Probiotic', alert: 'Final' },
  { doc: 82, feed: 61, action: '—', alert: '—' },
  { doc: 83, feed: 62, action: 'Mineral', alert: '—' },
  { doc: 84, feed: 63, action: '—', alert: '—' },
  { doc: 85, feed: 64, action: 'Probiotic', alert: '—' },
  { doc: 86, feed: 65, action: '—', alert: '—' },
  { doc: 87, feed: 66, action: 'Mineral', alert: '—' },
  { doc: 88, feed: 67, action: '—', alert: '—' },
  { doc: 89, feed: 68, action: 'Probiotic', alert: '—' },
  { doc: 90, feed: 65, action: 'Stop meds', alert: 'Harvest Prep' },
  { doc: 91, feed: 60, action: '—', alert: '—' },
  { doc: 92, feed: 58, action: '—', alert: '—' },
  { doc: 93, feed: 55, action: '—', alert: '—' },
  { doc: 94, feed: 50, action: '—', alert: '—' },
  { doc: 95, feed: 45, action: '—', alert: '—' },
  { doc: 96, feed: 40, action: '—', alert: '—' },
  { doc: 97, feed: 35, action: '—', alert: '—' },
  { doc: 98, feed: 30, action: '—', alert: '—' },
  { doc: 99, feed: 25, action: '—', alert: '—' },
  { doc: 100, feed: 20, action: 'Harvest', alert: 'Done' }
];
